cartApp/urls.py
from django.urls import path
from .views import *

app_name = 'cartApp'

urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>/', add, name='product_add'),
    path('remove/<product_id>/', remove, name='product_remove')
]

shopApp/urls.py
from django.urls import path
from .views import *

app_name = 'shopApp'

urlpatterns = [
    path('', product_in_category, name='product_all'),
    path('<slug:category_slug>/', product_in_category, name='product_in_category'),
    path('<int:id>/<product_slug>/', product_detail, name="product_detail"),
]

shopProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cartApp.urls')),
    path('', include('shopApp.urls')),
]

cartApp/models.py
from django.db import models

# Create your models here.

shopApp/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.fields import SlugField
from django.db.models.fields.files import ImageField
from django.db.models.fields.related import ForeignKey, create_many_to_many_intermediary_model
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    meta_description = models.TextField(blank=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True, allow_unicode=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shopApp:product_in_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='products')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True, allow_unicode=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    meta_description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available_display = models.BooleanField('Display', default=True)
    available_order = models.BooleanField('Order', default=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created', '-updated']
        index_together = [['id', 'slug']]

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shopApp:product_detail', args=[self.id, self.slug])

cartApp/forms.py
from django import forms

# 클라이언트 화면에 입력 폼을 만들어주려고
# 클라이언트가 입력한 데이터에 대한 전처리

class AddProductForm(forms.Form):
    quantity = forms.IntegerField()
    is_update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cartApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

# Create your views here.

from shopApp.models import Product
from .forms import AddProductForm
from .cart import Cart

@require_POST
def add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    form = AddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], is_update=cd['is_update'])

    return redirect('cartApp:detail')

def remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cartApp:detail')

def detail(request):
    cart = Cart(request)
    for product in cart:
        product['quantity_form'] = AddProductForm(initial={'quantity':product['quantity'], 'is_update':True})
    return render(request, 'cartApp/detail.html', {'cart':cart})

shopApp/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.

from .models import *
from cartApp.forms import AddProductForm

def product_in_category(request, category_slug=None):
    current_category = None
    cateogries = Category.objects.all()
    products = Product.objects.filter(available_display=True)
    if category_slug:
        current_category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=current_category)
    return render(request, 
    'shopApp/list.html',
    {
        'current_category':current_category,
        'categories':cateogries,
        'products':products
    })

def product_detail(request, id, product_slug=None):
    product = get_object_or_404(Product, id=id, slug=product_slug)
    add_to_cart = AddProductForm(initial={'quantity':1})
    return render(request, 'shopApp/detail.html', {'product':product, 'add_to_cart':add_to_cart})

cartApp/templates/cartApp/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Shopping cart
{% endblock %}

{% block content %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Image</th>
                <th scope="col">Product</th>
                <th scope="col">Quantity</th>
                <th scope="col">Remove</th>
                <th scope="col">Unit price</th>
                <th scope="col">Price</th>
            </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <th scope="row">
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{{ product.image.url }}" class="img-thumbnail">
                    </a>
                </th>
                <td>{{ product.name }}</td>
                <td>
                    <form action="{% url 'cartApp:product_add' product.id %}" method="post">
                        {{ item.quantity_form.quantity }}
                        {{ item.quantity_form.is_update }}
                        <input type="submit" class="btn btn-primary" value="Update">
                        {% csrf_token %}
                    </form>
                </td>
                <td><a href="{% url 'cartApp:product_remove' product.id %}">Remove</a></td>
                <td class="num">${{ item.price }}</td>
                <td class="num">${{ item.total_price }}</td>
            </tr>
            {% endwith %}
        {% endfor %}

        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price|floatformat:"2" }}</td>
        </tr>
        </tbody>
    </table>

    <p class="text-right">
        <a href='{% url "shopApp:product_all" %}' class="btn btn-secondary">Continue shopping</a>
    </p>
{% endblock %}

shopApp/templates/shopApp/detail.html
{% extends 'base.html' %}

{% block title %}Product Detail
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <img src="{{product.image.url}}" width="100%">
        </div>
        <div class="col">
            <h1 class="display-6">{{product.name}}</h1>
            <p><span class="badge badge-secondary">Price</span> {{product.price}}</p>

            <form action="{% url 'cartApp:product_add' product.id %}" method="post">
                {{add_to_cart}}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary btn-sm" value="Add to Cart">
            </form>

            <h5><span class="badge badge-secondary">Description</span>{{product.description|linebreaks}}</h5>
        </div>
    </div>
{% endblock %}

shopApp/templates/shopApp/list.html
{% extends 'base.html' %}
{% block title %}Category Page{% endblock %}
{% block content %}

<div class="row">
    <div class="col-2">
        <div class="list-group">
            <a href="/" class="list-group-item {% if not current_category %}active{% endif %}">All</a>
            {% for c in categories %}
            <a href="{{c.get_absolute_url}}"
                class="list-group-item {% if current_category.slug == c.slug %}active{% endif %}">{{c.name}}</a>
            {% endfor %}
        </div>
    </div>

    <div class="col">
        <div class="alert alert-info" role="alert">
            {% if current_category %}{{current_category.name}}{% else %}All Products{% endif %}
        </div>
        <div class="row">
            {% for product in products %}

            <div class="col-4">
                <div class="card">
                    {% if product.image %}<img class="card-img-top" src="{{product.image.url}}" alt="Product Image" height="150px">{% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{product.name}}</h5>
                        <p class="card-text">{{product.description}} <span
                                class="badge badge-secondary">${{product.price}}</span></p>
                        <a href="{{product.get_absolute_url}}" class="btn btn-primary">View Detail</a>
                    </div>
                </div>
            </div>

            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

    {% block script %}
    {% endblock %}

    {% block style %}
    {% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Django shop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav justify-content-end">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shopApp:product_all' %}">Product</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cartApp:detail' %}">Cart
                        {% if cart|length > 0 %}
                            ${{cart.get_product_total}} with {{cart|length}} items
                        {% else %}
                            : Empty
                        {% endif %}
                    </a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>

    <div class="container">
        {% block content%}
        {% endblock %}
    </div>

</body>

</html>